/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/6/14 10:09:13
 * UVersion : 2022.3.30f1
 *******************************************************/
using UnityEngine;
using FFramework;

namespace Game.Views
{

    /// <summary>
    /// 很好的一个试图
    /// </summary>
    public partial class MyView : Game.Views.CustomView
    {
		public UnityEngine.Transform @测试物体_Transform { get; private set; } = default;

        public virtual void Awake()
        {
			@测试物体_Transform = this.gameObject.GetComponent<UnityEngine.Transform>();
        }
    }
}
