/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/6/14 9:50:12
 * UVersion : 2022.3.30f1
 *******************************************************/
using UnityEngine;
using FFramework;

namespace Game.Views
{

    /// <summary>
    /// 很好的一个试图
    /// </summary>
    public partial class MyView : Game.Views.CustomView
    {
			

        public void InitRefs()
        {
				
        }
    }
}
