/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/6/14 8:43:15
 * UVersion : 2022.3.30f1
 *******************************************************/
using UnityEngine;
using FFramework;

namespace FFramework.Views
{

    /// <summary>
    /// 很好的一个试图
    /// </summary>
    public partial class MyView : FFramework.View
    {
			

        public void InitRefs()
        {
				
        }
    }
}
