
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace MiniDataTable.Audio
{
    public sealed partial class BGMRow : Luban.BeanBase
    {
        public BGMRow(ByteBuf _buf) 
        {
            Bgm = (Audio.EnumBGM)_buf.ReadInt();
            AssetPath = _buf.ReadString();
        }

        public static BGMRow DeserializeBGMRow(ByteBuf _buf)
        {
            return new Audio.BGMRow(_buf);
        }

        /// <summary>
        /// 背景音乐
        /// </summary>
        public readonly Audio.EnumBGM Bgm;
        /// <summary>
        /// 资源路径
        /// </summary>
        public readonly string AssetPath;
   
        public const int __ID__ = 1041244490;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Bgm:" + Bgm + ","
            + "AssetPath:" + AssetPath + ","
            + "}";
        }
    }

}
