
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Linq;


namespace MiniDataTable.Audio
{
    /// <summary>
    /// 背景音乐表
    /// </summary>
    public partial class TbBGM
    {
        private readonly System.Func<string, int, int, ByteBuf> _byteBufLoader;
        private readonly string _fileName;
        private Tables _tables;

        private readonly System.Collections.Generic.Dictionary<Audio.EnumBGM, Audio.BGMRow> _dataMap;
        private readonly System.Collections.Generic.Dictionary<Audio.EnumBGM, int> _offsetMap;
        private readonly System.Collections.Generic.Dictionary<Audio.EnumBGM, int> _lengthMap;

        private readonly System.Collections.Generic.List<Audio.BGMRow> _dataList;
    
        public TbBGM(ByteBuf _buf,string fileName, System.Func<string, int, int, ByteBuf> byteBufLoader)
        {
            _dataMap = new System.Collections.Generic.Dictionary<Audio.EnumBGM, Audio.BGMRow>();
            _offsetMap = new System.Collections.Generic.Dictionary<Audio.EnumBGM, int>();
            _lengthMap = new System.Collections.Generic.Dictionary<Audio.EnumBGM, int>();
            _fileName = fileName;
            _byteBufLoader = byteBufLoader;
        
            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                Audio.EnumBGM key;
                key = (Audio.EnumBGM)_buf.ReadInt();
                int offset = _buf.ReadInt();
                int length = _buf.ReadInt();
                _offsetMap.Add(key, offset);
                _lengthMap.Add(key, length);
            }
        }

        public void LoadAll(System.Action<Audio.EnumBGM,Audio.BGMRow> onLoad = null)
        {
            foreach(var key in _offsetMap.Keys)
		    {
                var value = this.Get(key);
                if (value != null)
			    {
				    onLoad?.Invoke(key, value);
			    }
		    }
        }

        public Audio.BGMRow GetOrDefault(Audio.EnumBGM key) => this.Get(key) ?? default;
        public Audio.BGMRow Get(Audio.EnumBGM key)
        {
            if (_dataMap.TryGetValue(key, out var v))
            {
                return v;
            }
            int offset = _offsetMap[key];
            int length = _lengthMap[key];
            ByteBuf buf = this._byteBufLoader(this._fileName, offset, length);
            v = Audio.BGMRow.DeserializeBGMRow(buf);;
            _dataMap[key] = v;
            v.ResolveRef(_tables);
            return v;
        }
        public Audio.BGMRow this[Audio.EnumBGM key] => this.Get(key);

        public void ResolveRef(Tables tables)
        {
            this._tables = tables;
        }

    }

}

