
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MiniDataTable.Audio
{ 
    /// <summary>
    /// 背景音乐
    /// </summary>
    public enum EnumBGM
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 战斗
        /// </summary>
        Battle = 10001,
        /// <summary>
        /// 登录
        /// </summary>
        Login = 10002,
    }

} 

