
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace MiniDataTable.Battle
{
    public sealed partial class EnemyGroupLvUpRow : Luban.BeanBase
    {
        public EnemyGroupLvUpRow(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            VictoryLevelMin = _buf.ReadInt();
            VictoryLevelMax = _buf.ReadInt();
            EnemyTypeCountMin = _buf.ReadInt();
            EnemyTypeCountMax = _buf.ReadInt();
            EnemyCountMin = _buf.ReadInt();
            EnemyCountMax = _buf.ReadInt();
            AttributeBoostRangeMin = _buf.ReadFloat();
            AttributeBoostRangeMax = _buf.ReadFloat();
            EXPReward = _buf.ReadInt();
            MoneyReward = _buf.ReadInt();
        }

        public static EnemyGroupLvUpRow DeserializeEnemyGroupLvUpRow(ByteBuf _buf)
        {
            return new Battle.EnemyGroupLvUpRow(_buf);
        }

        /// <summary>
        /// 配置编号
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 胜利次数最小值
        /// </summary>
        public readonly int VictoryLevelMin;
        /// <summary>
        /// 胜利次数最大值
        /// </summary>
        public readonly int VictoryLevelMax;
        /// <summary>
        /// 敌人种数最小值
        /// </summary>
        public readonly int EnemyTypeCountMin;
        /// <summary>
        /// 敌人种数最大值
        /// </summary>
        public readonly int EnemyTypeCountMax;
        /// <summary>
        /// 敌人个数最小值
        /// </summary>
        public readonly int EnemyCountMin;
        /// <summary>
        /// 敌人个数最大值
        /// </summary>
        public readonly int EnemyCountMax;
        /// <summary>
        /// 属性加成最小值
        /// </summary>
        public readonly float AttributeBoostRangeMin;
        /// <summary>
        /// 属性加成最大值
        /// </summary>
        public readonly float AttributeBoostRangeMax;
        /// <summary>
        /// 经验收益
        /// </summary>
        public readonly int EXPReward;
        /// <summary>
        /// 金币收益
        /// </summary>
        public readonly int MoneyReward;
   
        public const int __ID__ = 126461512;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "VictoryLevelMin:" + VictoryLevelMin + ","
            + "VictoryLevelMax:" + VictoryLevelMax + ","
            + "EnemyTypeCountMin:" + EnemyTypeCountMin + ","
            + "EnemyTypeCountMax:" + EnemyTypeCountMax + ","
            + "EnemyCountMin:" + EnemyCountMin + ","
            + "EnemyCountMax:" + EnemyCountMax + ","
            + "AttributeBoostRangeMin:" + AttributeBoostRangeMin + ","
            + "AttributeBoostRangeMax:" + AttributeBoostRangeMax + ","
            + "EXPReward:" + EXPReward + ","
            + "MoneyReward:" + MoneyReward + ","
            + "}";
        }
    }

}
