
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace MiniDataTable.Scene
{
    public sealed partial class SceneRow : Luban.BeanBase
    {
        public SceneRow(ByteBuf _buf) 
        {
            SceneName = (Scene.EnumScene)_buf.ReadInt();
        }

        public static SceneRow DeserializeSceneRow(ByteBuf _buf)
        {
            return new Scene.SceneRow(_buf);
        }

        /// <summary>
        /// 场景
        /// </summary>
        public readonly Scene.EnumScene SceneName;
   
        public const int __ID__ = 1440068880;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
        }

        public override string ToString()
        {
            return "{ "
            + "SceneName:" + SceneName + ","
            + "}";
        }
    }

}
