
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MiniDataTable.Scene
{ 
    /// <summary>
    /// 场景
    /// </summary>
    public enum EnumScene
    {
        /// <summary>
        /// 无
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 入口场景
        /// </summary>
        GameEntry = 1001,
        /// <summary>
        /// 登录场景
        /// </summary>
        Login = 1002,
        /// <summary>
        /// 战斗场景
        /// </summary>
        Battle = 1003,
    }

} 

