
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace MiniDataTable
{
    public partial class Tables
    {
        
        
        /// <summary>
        /// UI窗口表
        /// </summary>
        public UI.TbUIForm TbUIForm {get; }
        
        /// <summary>
        /// UI分组表
        /// </summary>
        public UI.TbUIGroup TbUIGroup {get; }
        
        /// <summary>
        /// 场景表
        /// </summary>
        public Scene.TbScene TbScene {get; }
        
        /// <summary>
        /// 战斗职业信息表
        /// </summary>
        public Battle.TbOccupation TbOccupation {get; }
        
        /// <summary>
        /// 敌人队伍信息表
        /// </summary>
        public Battle.TbEnemyGroupLvUp TbEnemyGroupLvUp {get; }
        
        /// <summary>
        /// 招募商店属性范围表
        /// </summary>
        public Cultivate.TbAttributeRange TbAttributeRange {get; }
        
        /// <summary>
        /// 招募商店升级表
        /// </summary>
        public Cultivate.TbRecruitLvUp TbRecruitLvUp {get; }
        
        /// <summary>
        /// 背景音乐表
        /// </summary>
        public Audio.TbBGM TbBGM {get; }
        public static readonly int TABLE_COUNT = 8;

        public Tables(System.Func<string, ByteBuf> offsetLoader,  System.Func<string, int, int, ByteBuf> byteBufLoader)
        {
            TbUIForm = new UI.TbUIForm(offsetLoader("ui_tbuiform"), "ui_tbuiform", byteBufLoader);
            TbUIGroup = new UI.TbUIGroup(offsetLoader("ui_tbuigroup"), "ui_tbuigroup", byteBufLoader);
            TbScene = new Scene.TbScene(offsetLoader("scene_tbscene"), "scene_tbscene", byteBufLoader);
            TbOccupation = new Battle.TbOccupation(offsetLoader("battle_tboccupation"), "battle_tboccupation", byteBufLoader);
            TbEnemyGroupLvUp = new Battle.TbEnemyGroupLvUp(offsetLoader("battle_tbenemygrouplvup"), "battle_tbenemygrouplvup", byteBufLoader);
            TbAttributeRange = new Cultivate.TbAttributeRange(offsetLoader("cultivate_tbattributerange"), "cultivate_tbattributerange", byteBufLoader);
            TbRecruitLvUp = new Cultivate.TbRecruitLvUp(offsetLoader("cultivate_tbrecruitlvup"), "cultivate_tbrecruitlvup", byteBufLoader);
            TbBGM = new Audio.TbBGM(offsetLoader("audio_tbbgm"), "audio_tbbgm", byteBufLoader);
            ResolveRef();
        }
    
        private void ResolveRef()
        {
            TbUIForm.ResolveRef(this);
            TbUIGroup.ResolveRef(this);
            TbScene.ResolveRef(this);
            TbOccupation.ResolveRef(this);
            TbEnemyGroupLvUp.ResolveRef(this);
            TbAttributeRange.ResolveRef(this);
            TbRecruitLvUp.ResolveRef(this);
            TbBGM.ResolveRef(this);
        }
    }

}
