
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MiniDataTable.UI
{ 
    public enum EnumUIGroup
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 全屏UI
        /// </summary>
        FullScreen = 1,
        /// <summary>
        /// 提示
        /// </summary>
        Tips = 2,
        /// <summary>
        /// 跑马灯
        /// </summary>
        Message = 3,
        /// <summary>
        /// 加载中
        /// </summary>
        Loading = 4,
        /// <summary>
        /// 最高层
        /// </summary>
        Top = 5,
        /// <summary>
        /// 弹窗
        /// </summary>
        Pop = 6,
    }

} 

