
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace MiniDataTable.UI
{ 
    public enum EnumUIForm
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 主菜单
        /// </summary>
        UIMainMenuForm = 1001,
        /// <summary>
        /// 设置
        /// </summary>
        UIOptionsForm = 1002,
        /// <summary>
        /// 关卡主界面
        /// </summary>
        UILevelMainForm = 1003,
        /// <summary>
        /// 暂停界面
        /// </summary>
        UIPausePanelForm = 1004,
        /// <summary>
        /// 战斗界面
        /// </summary>
        UICombatForm = 1005,
        /// <summary>
        /// 背包界面
        /// </summary>
        UIInventoryForm = 1006,
        /// <summary>
        /// 准备阶段菜单栏
        /// </summary>
        UIMenuBarForm = 1007,
        /// <summary>
        /// 招募商店界面
        /// </summary>
        UIRecruitForm = 1008,
        /// <summary>
        /// 战斗结算界面
        /// </summary>
        UISettleForm = 1009,
        /// <summary>
        /// 敌人队伍选择界面
        /// </summary>
        UIEnemyGroupForm = 1010,
    }

} 

