
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace MiniDataTable.UI
{
    public sealed partial class UIFormRow : Luban.BeanBase
    {
        public UIFormRow(ByteBuf _buf) 
        {
            UIFormName = (UI.EnumUIForm)_buf.ReadInt();
            AssetPath = _buf.ReadString();
            UIGroupName = (UI.EnumUIGroup)_buf.ReadInt();
            AllowMultiInstance = _buf.ReadBool();
            PauseCoveredUIForm = _buf.ReadBool();
        }

        public static UIFormRow DeserializeUIFormRow(ByteBuf _buf)
        {
            return new UI.UIFormRow(_buf);
        }

        /// <summary>
        /// 界面
        /// </summary>
        public readonly UI.EnumUIForm UIFormName;
        /// <summary>
        /// 资源路径
        /// </summary>
        public readonly string AssetPath;
        /// <summary>
        /// 界面组名称
        /// </summary>
        public readonly UI.EnumUIGroup UIGroupName;
        /// <summary>
        /// 是否允许多个界面实例
        /// </summary>
        public readonly bool AllowMultiInstance;
        /// <summary>
        /// 是否暂停被其覆盖的界面
        /// </summary>
        public readonly bool PauseCoveredUIForm;
   
        public const int __ID__ = -47496600;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "UIFormName:" + UIFormName + ","
            + "AssetPath:" + AssetPath + ","
            + "UIGroupName:" + UIGroupName + ","
            + "AllowMultiInstance:" + AllowMultiInstance + ","
            + "PauseCoveredUIForm:" + PauseCoveredUIForm + ","
            + "}";
        }
    }

}
