
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace MiniDataTable.UI
{
    public sealed partial class UIGroupRow : Luban.BeanBase
    {
        public UIGroupRow(ByteBuf _buf) 
        {
            UIGroupName = (UI.EnumUIGroup)_buf.ReadInt();
            Depth = _buf.ReadInt();
        }

        public static UIGroupRow DeserializeUIGroupRow(ByteBuf _buf)
        {
            return new UI.UIGroupRow(_buf);
        }

        /// <summary>
        /// UI组枚举
        /// </summary>
        public readonly UI.EnumUIGroup UIGroupName;
        /// <summary>
        /// 深度
        /// </summary>
        public readonly int Depth;
   
        public const int __ID__ = -1439674071;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "UIGroupName:" + UIGroupName + ","
            + "Depth:" + Depth + ","
            + "}";
        }
    }

}
